# Generated by Django 4.0.4 on 2023-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('job_category', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('education_level', models.CharField(max_length=200)),
                ('experience_time', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('shift', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
